taxi_riders:

  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{env_var('DBT_BQ_PROJECT')}}"
      dataset: dbt_dev_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile: "{{env_var('DBT_GOOGLE_KEYFILE')}}"

    pr:
      type: bigquery
      method: service-account
      project: "{{env_var('DBT_BQ_PROJECT')}}"
      dataset: dbt_pr_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile: "{{env_var('DBT_GOOGLE_KEYFILE')}}"

    prod:
      type: bigquery
      method: service-account
      project: "{{env_var('DBT_BQ_PROJECT')}}"
      dataset: dbt_prod_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile: "{{env_var('DBT_GOOGLE_KEYFILE')}}"

      
