base:
  branch: main
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
target:
  branch: dbt_datacamp_dev
  dbt:
    commands:
    - dbt deps
    - dbt build
  piperider:
    command: piperider run
