name: PR Transformation and Comparison
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    paths:
      - models/**
      - seeds/**
      - tests/**

env:
  DBT_BQ_PROJECT: ${{ vars.DBT_BQ_PROJECT }} 
  DBT_PROFILES_DIR: ./
  GOOGLE_SERVICE_ACCOUNT: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}


jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
    - name: checkout PR branch
      uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup DBT + Piperider
      run: |
        pip install dbt-bigquery
        pip install piperider['bigquery']
        dbt deps

    - run: dbt --version


    - name: Run DBT on PR environment
      run: dbt build --target pr

    - name: Profile on PR environment
      run: piperider run --datasource taxi_riders_pr --dbt-state target -o /tmp/pr-report/

    - name: Profile on PROD environment
      run: piperider run --datasource taxi_riders_prod -o /tmp/prod-report/

    - name: Compare and Prepare
      run: |
        piperider compare-reports \
          --debug \
          --base /tmp/prod-report/run.json \
          --target /tmp/pr-report/run.json \
          --output comparison-report/ \
          --tables-from target-only
        zip -r comparison-report.zip comparison-report/
    - uses: actions/upload-artifact@v3
      with:
        name: comparison-report-artifact
        path: comparison-report.zip

    - name: Prepare Comparison Summary
      run: |
        echo "# :bar_chart: Piperider Comparison Summary" > summary.md
        cat comparison-report/summary.md >> summary.md
        echo -e "\n" >> summary.md
        echo "## :paperclip: Generated Comparison Report ZIP" >> summary.md
        echo "Find it in the [Github Action Runs Page](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> summary.md
    - name: Create PR Comment
      uses: peter-evans/create-or-update-comment@v2.1.0
      with:
        issue-number: ${{ github.event.number }}
        body-file: summary.md