name: PR Transformation and Comparison
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    # paths:
    #   - models/**
    #   - seeds/**
    #   - tests/**

env:
  DBT_PROFILES_DIR: ./
  DBT_BQ_PROJECT: ${{ vars.DBT_BQ_PROJECT }} 
  DBT_GOOGLE_KEYFILE: /tmp/google/google-service-account.json
 # the contents of the keyfile pulled from GitHub Actions secrets 
  KEYFILE_CONTENTS: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}


jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
    # Prep Google keyfile
    - run: mkdir -p "$(dirname $DBT_GOOGLE_KEYFILE)" 
    - run: echo "$KEYFILE_CONTENTS" > $DBT_GOOGLE_KEYFILE
    
    - name: checkout PR branch
      uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup DBT + Piperider
      run: |
        pip install dbt-bigquery
        pip install piperider['bigquery']
        dbt deps

    - run: dbt --version


    - name: Run DBT on PR environment
      run: dbt build --target pr

    - name: Profile on PR environment
      run: piperider run --datasource taxi_riders_pr --dbt-state target -o /tmp/pr-report/
    
      # main branch
    - name: checkout main branch
      uses: actions/checkout@master
      with: 
        ref: main
      
    - name: install dbt deps
      run: dbt deps
    - name: Run DBT on PR environment
      run: dbt build --target prod

    - name: Profile on PROD environment
      run: piperider run --datasource taxi_riders_prod --dbt-state target -o /tmp/prod-report/

    # Compare
    - name: Compare and Prepare
      run: |
        piperider compare-reports \
          --base /tmp/prod-report/run.json \
          --target /tmp/pr-report/run.json \
          --output tmp/piperider/comparison \


    - name: Create PR Comment
      uses: LameSpy/create-or-update-comment@main
      with:
        issue-number: ${{ github.event.number }}
        body-file: tmp/piperider/comparison/summary.md

    - name: Create run artifact
      run: zip -r comparison-report.zip tmp/piperider/comparison/

    - name: Upload profiling result
      uses: actions/upload-artifact@v3
      with: 
        name: comparison-report-artifact
        path: comparison-report.zip